name: Code quality

on: [push]

jobs:

  runtests:
    runs-on: eclipse-temurin:21-jdk
    steps:
    - uses: actions/checkout@v3
    - name: Run tests with gradle wrapper
      run: |
        ./gradlew test
